spring:
  application:
    name: MyStudy
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  access-token-time: 600000
  refresh-token-time: 1209600000
